// Checklist content, generated from the Excel template (D-085-H.xlsx).
// Edit freely: add, remove or reword items.
//   id   = stable key. Do NOT rename once builds exist (old answers are linked by id).
//   help = explanation shown under the item.
//   sup  = false where the Excel had XXXXXXX (no supervisor check needed).

export const QC_SECTIONS = [
  { id: "centerpiece_top", title: "Centerpiece top", items: [
    { id: "centerpiece_top.cube_mounted_correctly", label: "Cube mounted correctly", help: "The cube is mounted with the correct screws and tightened enough.", sup: true },
    { id: "centerpiece_top.cube_cables_mounted_tight", label: "Cube cables mounted tight", help: "All cables and connectors going to the cube are secured tightly. Big loops cause vibrations in the cube.", sup: true },
    { id: "centerpiece_top.cube_channel_cables_glued", label: "Cube channel cables glued", help: "All channel connectors plugged into the cube need to be secured with hot glue.", sup: true },
    { id: "centerpiece_top.cube_connectors_fully_plugged_in", label: "Cube connectors fully plugged in", help: "Check if all connectors are fully plugged in and making contact.", sup: true },
    { id: "centerpiece_top.led_circuit_mounted_correctly", label: "LED circuit mounted correctly", help: "LEDs are mounted with the resistor on the left of the drone. The LED connectors are glued right way up and with an extra layer of epoxy.", sup: true },
    { id: "centerpiece_top.led_circuit_glued_correctly", label: "LED circuit glued correctly", help: "LED circuit is glued with the resistor on the left and the wires are neatly mounted.", sup: true },
    { id: "centerpiece_top.esc_phases_mounted_correctly", label: "ESC phases mounted correctly", help: "The ESC phase connectors are in the right orientation, flush to the surface and the screws are not sticking out of the holder.", sup: true },
    { id: "centerpiece_top.esc_s_mounted_correctly", label: "ESCs mounted correctly", help: "The ESCs are mounted straight and screwed tightly in the right orientation, the ESC should be numbered in motor order.", sup: true },
    { id: "centerpiece_top.esc_screws_secured", label: "ESC screws secured", help: "The ESC screws are secured with glue.", sup: true },
    { id: "centerpiece_top.esc_channels_marked", label: "ESC channels marked", help: "ESC channel cables are labelled with a numbered heat shrink.", sup: true },
    { id: "centerpiece_top.esc_correctly_connected", label: "ESC correctly connected", help: "ESC power cables are connected correctly on the PDB and cube.", sup: true },
    { id: "centerpiece_top.esc_power_cables_no_tension", label: "ESC power cables no tension", help: "No wires going to and from the ESC are under tension or rubbing against sharp corners.", sup: true },
    { id: "centerpiece_top.esc_power_cables_sleaved", label: "ESC power cables sleeved", help: "All cables going to and from the ESCs should be sleeved and protected from any damage over time.", sup: true },
    { id: "centerpiece_top.airbot_power_cables_plugged_in_correctly", label: "Airbot power cables plugged in correctly", help: "The right connectors are plugged in, check carefully so no wrong voltage goes to the wrong component. Connectors have to be fully clicked in.", sup: true },
    { id: "centerpiece_top.power_cables_marked_correctly", label: "Power cables marked correctly", help: "The power cables should be marked at the output connector of the cable and on the Airbot connector side of the cable.", sup: true },
    { id: "centerpiece_top.power_cables_sleaved", label: "Power cables sleeved", help: "All cables going to and from the PDB should be sleeved and protected from any damage over time.", sup: true },
    { id: "centerpiece_top.pdb_screws_torqued_secured", label: "PDB screws torqued & secured", help: "The PDB screws are mounted with crinkle washers and torqued to 0.8 Nm. Afterwards they are marked with marking paint.", sup: false },
    { id: "centerpiece_top.pdb_divider_installed", label: "PDB divider installed", help: "The PDB divider is mounted to prevent short circuits.", sup: true },
    { id: "centerpiece_top.main_power_cables_mounted_correctly", label: "Main power cables mounted correctly", help: "The main power cables from the battery box are mounted correctly. Red on top, Black on the bottom.", sup: true },
    { id: "centerpiece_top.battery_connectors_mounted_correctly", label: "Battery connectors mounted correctly", help: "The battery connectors are all in good condition, straight and inserted all the way into the battery box/connector holder.", sup: true },
    { id: "centerpiece_top.stand_screws_tightened_correctly", label: "Stand screws tightened correctly", help: "Stand screws are mounted with plastic washer, blue Loctite and tightened.", sup: true },
    { id: "centerpiece_top.connectors_are_labelled", label: "Connectors are labelled", help: "All connectors are labelled to make maintenance/repairs easier.", sup: true },
    { id: "centerpiece_top.all_cables_sleaved_and_safely_secured", label: "All cables sleeved and safely secured", help: "All cables should be sleeved and protected from any damage over time.", sup: true },
    { id: "centerpiece_top.system_looks_tidy", label: "System looks tidy", help: "Overall looks of the system are organized and tidy. Make it look as good as it works.", sup: true },
    { id: "centerpiece_top.pictures_taken", label: "Pictures taken", help: "Pictures are taken and stored for any future info about the system's internals.", sup: true },
  ]},
  { id: "centerpiece_bottom", title: "Centerpiece bottom", items: [
    { id: "centerpiece_bottom.antenna_s_mounted_correctly", label: "Antennas mounted correctly", help: "All antennas in the system are installed and plugged in all the way.", sup: true },
    { id: "centerpiece_bottom.temp_relay_set_at_40_degrees", label: "Temp relay set at 40 degrees", help: "Temp relay is set at 40 degrees and temp sensor is mounted in the centerpiece top.", sup: true },
    { id: "centerpiece_bottom.connectors_are_labelled", label: "Connectors are labelled", help: "All connectors are labelled to make maintenance/repairs easier.", sup: true },
    { id: "centerpiece_bottom.all_cables_sleaved_and_safely_secured", label: "All cables sleeved and safely secured", help: "All cables should be sleeved and protected from any damage over time.", sup: true },
    { id: "centerpiece_bottom.system_looks_tidy", label: "System looks tidy", help: "Overall looks of the system are organized and tidy. Make it look as good as it works.", sup: true },
    { id: "centerpiece_bottom.pictures_taken", label: "Pictures taken", help: "Pictures are taken and stored for any future info about the system's internals.", sup: true },
  ]},
  { id: "hybrid_only", title: "Hybrid only", items: [
    { id: "hybrid_only.gcu_phase_orientation", label: "GCU Phase orientation", help: "GCU phase wiring is connected correctly, wires are labelled 1-6.", sup: true },
    { id: "hybrid_only.load_sensor_mounted_correct", label: "Load sensor mounted correctly", help: "Current sensor is wired in the right orientation. The screws are mounted with the correct lockrings and secured with epoxy.", sup: true },
    { id: "hybrid_only.can_cables_are_connected_securely", label: "CAN cables are connected securely", help: "All hybrid components are connected and all CAN connectors are screwed in.", sup: true },
    { id: "hybrid_only.engine_telem_cable_connected", label: "Engine telem cable connected", help: "The engine telemetry serial cable is wired to the cube.", sup: true },
    { id: "hybrid_only.start_trigger_cable_connected", label: "Start trigger cable connected", help: "Start trigger cable is connected (standard CH10).", sup: true },
    { id: "hybrid_only.fan_servo_cables_connected", label: "Fan servo cables connected", help: "Fan servo connectors are connected (standard CH11&CH12).", sup: true },
    { id: "hybrid_only.fan_power_jst_connected", label: "Fan power JST connected", help: "JST power for the fans is connected to battery voltage.", sup: true },
    { id: "hybrid_only.sd_card_is_installed", label: "SD card is installed", help: "SD card is installed in the supervisor unit.", sup: true },
    { id: "hybrid_only.gcu_serial_number_documented", label: "GCU serial number documented", help: "GCU serial number is documented.", sup: true },
  ]},
  { id: "general", title: "General", items: [
    { id: "general.screws_mounted_with_loctite", label: "Screws mounted with Loctite", help: "Check two random screws and check if they are mounted with the correct Loctite, replace with new Loctite.", sup: true },
    { id: "general.serial_nr_custom_engraving", label: "Serial nr / custom engraving", help: "Serial number is engraved in the system or customer custom engraving is done.", sup: true },
    { id: "general.stickers_pasted", label: "Stickers pasted", help: "All stickers are pasted in the right position.", sup: false },
  ]},
  { id: "booms", title: "Booms", items: [
    { id: "booms.prop_qr_mounted_correct", label: "Prop QR mounted correct", help: "Propeller quick release is mounted securely and in the right order.", sup: false },
    { id: "booms.motor_connectors_mounted_correct", label: "Motor connectors mounted correct", help: "Motor bullet connectors are tightly mounted and straight in the connector.", sup: false },
    { id: "booms.led_connector_mounted_correct", label: "LED connector mounted correct", help: "The LED connector in the boom connector is mounted right way up and glued in position.", sup: false },
    { id: "booms.boom_qr_plate_glued", label: "Boom QR plate glued", help: "Boom QR plate is mounted with epoxy.", sup: false },
    { id: "booms.boom_qr_screw_set", label: "Boom QR screw set", help: "When all booms are mounted on the centerpiece, The QR is set at the right tightness.", sup: true },
  ]},
];

export const PROGRAMMING = [
  { id: "programming.firmware_installed", label: "Firmware installed" },
  { id: "programming.parameters_installed", label: "Parameters installed" },
  { id: "programming.brd_serial_nr_set", label: "BRD serial nr set" },
  { id: "programming.accels_level_calibrated", label: "Accels & level calibrated" },
  { id: "programming.remote_controller_installed", label: "Remote controller installed" },
  { id: "programming.radio_calibration_controller", label: "Radio calibration controller" },
  { id: "programming.radio_calibration_mp", label: "Radio calibration MP" },
  { id: "programming.battery_monitor_calibrated", label: "Battery monitor calibrated" },
  { id: "programming.battery_failsave_tested", label: "Battery failsafe tested" },
  { id: "programming.compass_order_set", label: "Compass order set" },
  { id: "programming.gps_position_set", label: "GPS position set" },
  { id: "programming.compass_calibrated", label: "Compass calibrated" },
  { id: "programming.led_s_switch_working", label: "LEDs (switch) working" },
  { id: "programming.motor_direction_order", label: "Motor direction & order" },
  { id: "programming.all_options_are_working", label: "All options are working" },
];

export const INDOOR_TEST = [
  { id: "indoor.kill_switch_test", label: "Kill switch test" },
  { id: "indoor.half_arm_check", label: "Half arm check" },
  { id: "indoor.full_arm_check", label: "Full arm check" },
  { id: "indoor.flying_directions", label: "Flying directions" },
  { id: "indoor.half_throttle", label: "Half throttle" },
  { id: "indoor.leds_switch_working", label: "LEDs (switch) working" },
  { id: "indoor.retract_working", label: "Retract working" },
];

export const FINAL_ASSEMBLY = [
  { id: "pre_first_start_checks", title: "Pre- first start checks", items: [
    { id: "pre_first_start_checks.air_filter_oiled_dust_cover_installed", label: "Air filter oiled / Dust cover installed", help: "Twin Air air filter is properly oiled and installed with a Panduit zip tie, Dust cover is installed afterwards." },
    { id: "pre_first_start_checks.intake_block_off_plate_installed", label: "Intake block off plate installed", help: "The intake block off plate is installed underneath the air filter." },
    { id: "pre_first_start_checks.coolant_level_checked", label: "Coolant level checked", help: "The coolant level is topped off and checked at the radiator cap." },
    { id: "pre_first_start_checks.fuel_filter_flow_direction_correct", label: "Fuel filter flow direction correct", help: "The arrow on the fuel filter indicating the fuel flow is towards the injector." },
    { id: "pre_first_start_checks.cooling_hose_zip_ties_mounted", label: "Cooling hose zip ties mounted", help: "The cooling lines are secured with two 3.6 mm Panduit zip ties per fitting." },
    { id: "pre_first_start_checks.pegasus_wires_glued", label: "Pegasus wires glued", help: "The generator wires and throttle body wires are secured with silicone." },
    { id: "pre_first_start_checks.hour_meter_turned_on", label: "Hour meter turned on", help: "The hour meter is activated so the runtime is being logged." },
    { id: "pre_first_start_checks.hopper_tank_leak_proof", label: "Hopper tank leak proof", help: "Fill the tank with fuel and check for any leaks. No amount of leak is acceptable." },
    { id: "pre_first_start_checks.exhaust_bolts_tightened", label: "Exhaust bolts tightened", help: "The spring washer is compressed all the way." },
    { id: "pre_first_start_checks.exhaust_o_ring_mounted_correct", label: "Exhaust O-ring mounted correctly", help: "The O-Ring is not pressed out underneath the exhaust flange." },
    { id: "pre_first_start_checks.spark_plug_caps_installed_correct", label: "Spark plug caps installed correct", help: "Press down on the spark plug caps so they are mounted all the way." },
    { id: "pre_first_start_checks.main_fuel_line_doesn_t_rub", label: "Main fuel line doesn't rub", help: "Follow the main fuel line going into the injector to make sure that it is not rubbing against sharp edges, pay attention to the intake hose zip tie." },
    { id: "pre_first_start_checks.cables_dont_rub_against_sharp_edges", label: "Cables don't rub against sharp edges", help: "No cables are rubbing or are in danger of being damaged when system is running/vibrating." },
  ]},
  { id: "general_final_checks", title: "General final checks", items: [
    { id: "general_final_checks.4mm_foam_under_gps_holders", label: "4 mm foam under GPS holders", help: "4 mm foam is installed between the GPS holder and the centerpiece." },
    { id: "general_final_checks.heat_insulating_tape_on_cooling_fans", label: "Heat insulating tape on cooling fans", help: "The gold heat insulating tape is mounted on the cooling fans oriented with the round side to the front of the drone." },
    { id: "general_final_checks.payload_star_qr_mounted_correctly", label: "Payload star & QR mounted correctly", help: "The QR is adjusted properly and facing the correct direction with the directional slot to the front of the system." },
    { id: "general_final_checks.water_drain_line_snakeskinned", label: "Water drain line snakeskinned", help: "The water drainage line is sleeved with snakeskin sleeving." },
    { id: "general_final_checks.can_cables_secured", label: "CAN cables secured", help: "The CAN cables to the Engine, CDI and water pump are locked in with the lockscrews." },
    { id: "general_final_checks.fan_connectors_secured_with_glue", label: "Fan connectors secured with glue", help: "The power and servo connectors are secured with a drop of hot glue." },
    { id: "general_final_checks.heat_shield_mounted", label: "Heat shield mounted", help: "The heat shield is mounted with the gold heat insulating tape on the engine dampening plate." },
    { id: "general_final_checks.engine_phases_waterproofed", label: "Engine phases waterproofed", help: "The phase holder print is sealed with montagekit." },
    { id: "general_final_checks.cooling_lines_protected_with_tape", label: "Cooling lines protected with tape", help: "The cooling lines are protected with stoftape on the correct locations." },
    { id: "general_final_checks.gps_antenna_cables_bundled", label: "GPS/antenna cables bundled", help: "The wires coming from the GPS holder are neatly bundled together with a zip tie." },
    { id: "general_final_checks.main_fuel_line_secured_with_zip_ties", label: "Main fuel line secured with zip ties", help: "The fuel line is mounted in the fuel line holder and secured with all the zip ties." },
    { id: "general_final_checks.engine_serial_number_documented", label: "Engine serial number documented", help: "Engine serial number is documented in the build info sheet." },
    { id: "general_final_checks.cooling_fan_caps_glued", label: "Cooling fan caps glued", help: "The cooling fan caps/crowns are secured and mounted correctly." },
    { id: "general_final_checks.fuel_tank_locks_installed", label: "Fuel tank locks installed", help: "Fuel tank locking pins are installed." },
    { id: "general_final_checks.fuel_tanks_fitted_and_qr_tested", label: "Fuel tanks fitted and QR tested", help: "The corresponding fuel tanks have been fitted on the system. The quick releases lock all the way." },
    { id: "general_final_checks.akrapovic_logo_removed_military_only", label: "Akrapovic logo removed (military only)", help: "Grind away the Akrapovic marking on the back of the exhaust and paint over underneath the carbon heat shield." },
  ]},
];
